name: Build

on:
  pull_request:
    branches: [ prod ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Add temp files for build
        run: |
          mkdir dist
          touch dist/tmp.tmp

      - name: Build docker image
        run: | 
          chmod +x ./build.sh
          ./build.sh
