name: Build

on:
  pull_request:
    branches: [ prod ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: | 
          mkdir dist
          chmod +x ./build.sh
          ./build.sh
